CREATE TABLE ITENS (
    ITEM                       VARCHAR2(20)   NOT NULL,
    CONJUNTO                   VARCHAR2(20)   NOT NULL,
	IDTIPOFT2                  NUMBER         NULL,
    IDTIPOIPI                  NUMBER         NULL,
    IDCLASSFISCAL              NUMBER         NULL,
    IDFAMILIA                  NUMBER         NULL,
    ESTADOFT_DETEC             NUMBER         NOT NULL,
    TEXTOESTADOFT_DETEC        VARCHAR2(30)   NULL,
    RAZAOESTADOFT              VARCHAR2(4000) NOT NULL,
    STATUSFT                   NUMBER(3)      NULL,
    TEXTOSTATUSFT              VARCHAR2(200)  NULL,
    VERSAO                     NUMBER         NOT NULL,
    OBSVERSAO                  VARCHAR2(4000) NULL,
    IDCLIENTE                  NUMBER         NOT NULL,
    REFERENCIA                 VARCHAR2(125)  NOT NULL,
    CODIGOREFERENCIA           VARCHAR2(30)   NULL,
    TIPOABNT                   VARCHAR2(5)    NULL,
    PECASPORUNIDADE            BINARY_DOUBLE  NULL,
    UNIDADESPORCONJUNTO        BINARY_DOUBLE  NULL,
    PECASPORCONJUNTO           BINARY_DOUBLE  NULL,
    EXIGELAUDO                 NUMBER(5)      NOT NULL,
    GRAMATURA                  NUMBER         NULL,
    MULLENMINIMO               BINARY_DOUBLE  NULL,
    COLUNAMINIMO               BINARY_DOUBLE  NULL,
    COBBINTMAXIMO              BINARY_DOUBLE  NULL,
    COBBEXTMAXIMO              BINARY_DOUBLE  NULL,
    ESPESSURA                  BINARY_DOUBLE  NULL,
	COMPRESSAO                 BINARY_DOUBLE  NULL,
    COMPOSICAO                 VARCHAR2(40)   NULL,
    LARGURA                    NUMBER         NULL,
    REFILOLARGURA              NUMBER         NOT NULL,
    COMPRIMENTO                NUMBER         NULL,
    REFILOCOMPRIMENTO          NUMBER         NOT NULL,
    MULTLARG                   NUMBER         NOT NULL,
    MULTCOMP                   NUMBER         NOT NULL,
    ARRANJO                    NUMBER         NULL,
    REFUGOCLIENTE              BINARY_DOUBLE  NOT NULL,
    VINCOLARG1                 NUMBER         NULL,
    VINCOLARG2                 NUMBER         NULL,
    VINCOLARG3                 NUMBER         NULL,
    VINCOCOMP1                 NUMBER         NULL,
    VINCOCOMP2                 NUMBER         NULL,
    VINCOCOMP3                 NUMBER         NULL,
    VINCOCOMP4                 NUMBER         NULL,
    VINCOCOMP5                 NUMBER         NULL,
    LAP                        NUMBER         NOT NULL,
	PROLONGLAP                 NUMBER         NOT NULL,
    LAPNOCOMP                  NUMBER(5)      NOT NULL,
    TEXTO_LAPNOCOMP            VARCHAR2(30)   NULL,
    LAPINTERNO                 NUMBER(5)      NOT NULL,
    TEXTO_LAPINTERNO           VARCHAR2(30)   NULL,
    LAPPRIMVINCO               NUMBER(5)      NOT NULL,
    REFILADO                   NUMBER(5)      NOT NULL,
	RESINAINTERNA              NUMBER         NOT NULL,
	FECHAMENTO                 VARCHAR2(30)   NULL,
    AMARRADO                   NUMBER(5)      NOT NULL,
    FITILHOSLARGPACOTE         NUMBER         NULL,
    PALETIZADO                 NUMBER(5)      NOT NULL,
    PACOTESLARGURA             NUMBER         NULL,
    PACOTESCOMPRIMENTO         NUMBER         NULL,
    PACOTESALTURA              NUMBER         NULL,
    PECASPORPACOTE             NUMBER         NULL,
    PECASPORPALETE             NUMBER         NULL,
    PACOTESPORPALETE           NUMBER         NULL,
    UNIDADESPORPALETE          BINARY_DOUBLE  NULL,
    FITASLARGPALETE            NUMBER         NULL,
    FITASCOMPPALETE            NUMBER         NULL,
    ESPELHO                    NUMBER(5)      NOT NULL,
    FILME                      NUMBER(5)      NOT NULL,
    FACA                       VARCHAR2(30)   NULL,
    CODFI                      VARCHAR2(30)   NULL,
    COR1                       VARCHAR2(15)   NULL,
	CONSUMOCOR1                NUMBER         NULL,
	COR2                       VARCHAR2(15)   NULL,
    CONSUMOCOR2                NUMBER         NULL,
    COR3                       VARCHAR2(15)   NULL,
    CONSUMOCOR3                NUMBER         NULL,
    COR4                       VARCHAR2(15)   NULL,
    CONSUMOCOR4                NUMBER         NULL,
    NRCORES                    NUMBER         NULL,
    TOLMAIS                    NUMBER         NOT NULL,
    TOLMENOS                   NUMBER         NOT NULL,
    TIPOOBS1                   VARCHAR2(15)   NULL,
    OBS1                       VARCHAR2(255)  NULL,
    TIPOOBS2                   VARCHAR2(15)   NULL,
    OBS2                       VARCHAR2(255)  NULL,
    TIPOOBS3                   VARCHAR2(15)   NULL,
    OBS3                       VARCHAR2(255)  NULL,
    TIPOOBS4                   VARCHAR2(15)   NULL,
    OBS4                       VARCHAR2(255)  NULL,
    TIPOOBS5                   VARCHAR2(15)   NULL,
    LARGURAINTERNA             NUMBER         NULL,
    COMPRIMENTOINTERNO         NUMBER         NULL,
    ALTURAINTERNA              NUMBER         NULL,
    LARGPECA                   NUMBER         NULL,
    COMPPECA                   NUMBER         NULL,
    DIMADIC1                   NUMBER         NULL,
    DIMADIC2                   NUMBER         NULL,
    IMPRIMELOGOTIPO            NUMBER         NOT NULL,
    USUARIOCRIACAO             NUMBER         NULL,
    USUARIO                    NUMBER         NULL,
    DATAMODIF                  DATE           NULL,
    DATACRIACAO                DATE           NULL,
    COMPPACOTE                 NUMBER         NULL,
    LARGPACOTE                 NUMBER         NULL,
    ALTURAPACOTE               NUMBER         NULL,
    COMMPALETEFECHADO          NUMBER         NULL,
    LARGPALETEFECHADO          NUMBER         NULL,
    ALTURAPALETEFECHADO        NUMBER         NULL,
    PESOCAIXA                  BINARY_DOUBLE  NULL,
    PROJETO                    VARCHAR2(50)   NULL,
    DESCRTRAVACOMPOSICAO       VARCHAR2(50)   NULL,
    PATHFIGURADOLASTRO         VARCHAR2(255)  NULL,
    EMPILHAMENTOMAXIMO         NUMBER         NULL,
    IDPALETE                   NUMBER         NULL,
    IDUNICOREGISTRO            RAW(16)        NOT NULL,
    NRPEDSPILOTO               NUMBER         NULL,
    AREABRUTAPECACOMREFILOS    BINARY_DOUBLE  NULL,
    AREABRUTAPECA              BINARY_DOUBLE  NULL,
    AREALIQUIDAPECA            BINARY_DOUBLE  NULL,
    AREABRUTACHAPA             BINARY_DOUBLE  NULL,
    AREALIQUIDACHAPA           BINARY_DOUBLE  NULL,
    VOLUMEPALETEFECHADOM3      BINARY_DOUBLE  NULL,
    VOLUMEPACOTEFECHADOM3      BINARY_DOUBLE  NULL,
    RESUMOCHAPA                NUMBER         NULL,
    COMPLEMENTOCHAPA           NUMBER         NULL,
    CONSTRAINT PK_ITENS PRIMARY KEY (ITEM)
)
