from datetime import datetime
from airflow import DAG
from airflow.providers.common.sql.operators.sql import SQLExecuteQueryOperator

ORACLE_CONN_ID = "oracle_raw"

CREATE_TABLE_SQL = """
DECLARE
  e_already_exists EXCEPTION;
  PRAGMA EXCEPTION_INIT(e_already_exists, -955);
BEGIN
  EXECUTE IMMEDIATE q'[
    CREATE TABLE RAW_PRODUTOS (
      ID            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
      TIPO          VARCHAR2(30)  NOT NULL,
      NOME          VARCHAR2(100) NOT NULL,
      GRAMATURA     NUMBER(6,2),
      DATA_CRIACAO  DATE DEFAULT SYSDATE,
      CONSTRAINT PK_RAW_PRODUTOS PRIMARY KEY (ID)
    )
  ]';
EXCEPTION WHEN e_already_exists THEN NULL;
END;
"""

SEED_DATA_SQL = """
BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE RAW_PRODUTOS';
  INSERT INTO RAW_PRODUTOS (TIPO, NOME, GRAMATURA) VALUES ('PAPEL',   'Sulfite A4',            75);
  INSERT INTO RAW_PRODUTOS (TIPO, NOME, GRAMATURA) VALUES ('PAPEL',   'Couchê Brilho',        150);
  INSERT INTO RAW_PRODUTOS (TIPO, NOME, GRAMATURA) VALUES ('PAPELÃO', 'Ondulado Simple Face', 300);
  INSERT INTO RAW_PRODUTOS (TIPO, NOME, GRAMATURA) VALUES ('PAPELÃO', 'Micro-ondulado B',     400);
  INSERT INTO RAW_PRODUTOS (TIPO, NOME, GRAMATURA) VALUES ('PAPEL',   'Cartão Triplex',       250);
  COMMIT;
END;
"""

with DAG(
    dag_id="raw_produtos_seed",
    start_date=datetime(2025, 1, 1),
    schedule=None,
    catchup=False,
    description="Cria RAW_PRODUTOS e insere 5 linhas de teste (Oracle via Common SQL)",
    tags=["oracle","raw"],
):
    create_table = SQLExecuteQueryOperator(
        task_id="create_table_raw_produtos",
        conn_id=ORACLE_CONN_ID,
        sql=CREATE_TABLE_SQL,
    )

    seed_data = SQLExecuteQueryOperator(
        task_id="seed_raw_produtos",
        conn_id=ORACLE_CONN_ID,
        sql=SEED_DATA_SQL,
    )

    create_table >> seed_data
