CREATE TABLE REFINED.CLIENTES (
  IDCLIENTE          NUMBER        NOT NULL,
  CLIENTE            VARCHAR2(50)  NOT NULL,
  CODCLIENTE         VARCHAR2(30)  NOT NULL,
  CODREPRESENTANTE   NUMBER        NULL,
  CONSTRAINT PK_CLIENTES_REFINED PRIMARY KEY (IDCLIENTE)
);
