CREATE TABLE REFINED.FACAS (
  CODFACA       VARCHAR2(30)  NOT NULL,
  STATUS        NUMBER        NULL,
  COMPLAMINA    NUMBER        NULL,
  DESATIVADOSN  CHAR(1)       NOT NULL,
  CONSTRAINT PK_REFINED_FACAS PRIMARY KEY (CODFACA)
);
