CREATE TABLE REFINED.ITENS (
  ITEM                       VARCHAR2(20)   NOT NULL,
  IDTIPOFT2                  NUMBER         NULL,
  IDFAMILIA                  NUMBER         NULL,
  ESTADOFT_DETEC             NUMBER         NOT NULL,
  TEXTOESTADOFT_DETEC        VARCHAR2(30)   NULL,
  STATUSFT                   NUMBER(3)      NULL,
  TEXTOSTATUSFT              VARCHAR2(200)  NULL,
  IDCLIENTE                  NUMBER         NOT NULL,
  REFERENCIA                 VARCHAR2(125)  NOT NULL,
  CODIGOREFERENCIA           VARCHAR2(30)   NULL,
  TIPOABNT                   VARCHAR2(5)    NULL,
  EXIGELAUDO                 NUMBER(5)      NOT NULL,
  GRAMATURA                  NUMBER         NULL,
  COLUNAMINIMO               BINARY_DOUBLE  NULL,
  COBBINTMAXIMO              BINARY_DOUBLE  NULL,
  COMPRESSAO                 BINARY_DOUBLE  NULL,
  COMPOSICAO                 VARCHAR2(40)   NULL,
  LARGURA                    NUMBER         NULL,
  REFILOLARGURA              NUMBER         NOT NULL,
  COMPRIMENTO                NUMBER         NULL,
  REFILOCOMPRIMENTO         NUMBER          NOT NULL,
  MULTLARG                   NUMBER         NOT NULL,
  MULTCOMP                   NUMBER         NOT NULL,
  ARRANJO                    NUMBER         NULL,
  REFUGOCLIENTE              BINARY_DOUBLE  NOT NULL,
  VINCOLARG1                 NUMBER         NULL,
  VINCOLARG2                 NUMBER         NULL,
  VINCOLARG3                 NUMBER         NULL,
  VINCOCOMP1                 NUMBER         NULL,
  VINCOCOMP2                 NUMBER         NULL,
  VINCOCOMP3                 NUMBER         NULL,
  VINCOCOMP4                 NUMBER         NULL,
  VINCOCOMP5                 NUMBER         NULL,
  LAP                        NUMBER         NOT NULL,
  PROLONGLAP                 NUMBER         NOT NULL,
  LAPNOCOMP                  NUMBER(5)      NOT NULL,
  LAPINTERNO                 NUMBER(5)      NOT NULL,
  REFILADO                   NUMBER(5)      NOT NULL,
  RESINAINTERNA              NUMBER         NOT NULL,
  AMARRADO                   NUMBER(5)      NOT NULL,
  PALETIZADO                 NUMBER(5)      NOT NULL,
  PACOTESLARGURA             NUMBER         NULL,
  PACOTESCOMPRIMENTO         NUMBER         NULL,
  PACOTESALTURA              NUMBER         NULL,
  PECASPORPACOTE             NUMBER         NULL,
  PECASPORPALETE             NUMBER         NULL,
  PACOTESPORPALETE           NUMBER         NULL,
  UNIDADESPORPALETE          BINARY_DOUBLE  NULL,
  ESPELHO                    NUMBER(5)      NOT NULL,
  FILME                      NUMBER(5)      NOT NULL,
  FACA                       VARCHAR2(30)   NULL,
  COR1                       VARCHAR2(15)   NULL,
  CONSUMOCOR1                NUMBER         NULL,
  COR2                       VARCHAR2(15)   NULL,
  CONSUMOCOR2                NUMBER         NULL,
  COR3                       VARCHAR2(15)   NULL,
  CONSUMOCOR3                NUMBER         NULL,
  COR4                       VARCHAR2(15)   NULL,
  CONSUMOCOR4                NUMBER         NULL,
  NRCORES                    NUMBER         NULL,
  LARGURAINTERNA             NUMBER         NULL,
  COMPRIMENTOINTERNO         NUMBER         NULL,
  ALTURAINTERNA              NUMBER         NULL,
  LARGPECA                   NUMBER         NULL,
  COMPPECA                   NUMBER         NULL,
  COMPPACOTE                 NUMBER         NULL,
  LARGPACOTE                 NUMBER         NULL,
  ALTURAPACOTE               NUMBER         NULL,
  COMMPALETEFECHADO          NUMBER         NULL,
  LARGPALETEFECHADO          NUMBER         NULL,
  ALTURAPALETEFECHADO        NUMBER         NULL,
  PESOCAIXA                  BINARY_DOUBLE  NULL,
  PATHFIGURADOLASTRO         VARCHAR2(255)  NULL,
  IDPALETE                   NUMBER         NULL,
  AREABRUTAPECACOMREFILOS    BINARY_DOUBLE  NULL,
  AREABRUTAPECA              BINARY_DOUBLE  NULL,
  AREALIQUIDAPECA            BINARY_DOUBLE  NULL,
  AREABRUTACHAPA             BINARY_DOUBLE  NULL,
  AREALIQUIDACHAPA           BINARY_DOUBLE  NULL,
  VOLUMEPALETEFECHADOM3      BINARY_DOUBLE  NULL,
  VOLUMEPACOTEFECHADOM3      BINARY_DOUBLE  NULL,
  CONSTRAINT PK_REFINED_ITENS PRIMARY KEY (ITEM)
);
