CREATE TABLE REFINED.MAQUINA (
  MAQUINA         VARCHAR2(50)  NOT NULL,
  TIPO            NUMBER        NOT NULL,
  NRDECORES       NUMBER        NULL,
  IDGRUPOMAQUINA  NUMBER        NULL,
  CONSTRAINT PK_REFINED_MAQUINA PRIMARY KEY (MAQUINA)
);
