CREATE TABLE REFINED.PARADAS (
  PARADA          NUMBER        NOT NULL,
  DESCRICAO       VARCHAR2(30)  NULL,
  USADACONVERSAO  CHAR(1)       NOT NULL,
  DESATIVADA      CHAR(1)       NOT NULL,
  FLAGEXTERNA     CHAR(1)       NOT NULL,
  CONSTRAINT PK_REFINED_PARADAS PRIMARY KEY (PARADA)
);
