CREATE TABLE REFINED.TAREFCON (
  MAQUINA                 VARCHAR2(50)   NOT NULL,
  FLAGPARADA              NUMBER(5)      NOT NULL,
  CODIGOPARADAOUCONV      NUMBER,
  TURMA                   VARCHAR2(5)    NOT NULL,
  OP                      VARCHAR2(45),
  PEDIDO                  VARCHAR2(21),
  ITEM                    VARCHAR2(20),
  REPROGRAMACAO           NUMBER,
  ARRANJO                 NUMBER,
  GRAMATURA               NUMBER,
  QUANTIDADEPROGRAMADA    NUMBER,
  CHAPASALIMENTADAS       NUMBER,
  QUANTIDADEPRODUZIDA     NUMBER,
  QUANTIDADEAJUSTE        NUMBER,
  DURACAOPREVISTA         NUMBER,
  INICIO                  DATE           NOT NULL,
  FIM                     DATE           NOT NULL,
  DIADATURMA              DATE           NOT NULL,
  IDCLIENTE               NUMBER,
  USUARIO                 NUMBER,
  ORIGEMREGISTRO          NUMBER,
  DESCORIGEMREGISTRO      VARCHAR2(100),
  SKIPFEED                NUMBER(5)      NOT NULL,
  OPONDULADA              VARCHAR2(45),
  DURACAO                 NUMBER,
  FACA                    VARCHAR2(30)
);

