CREATE TABLE ITENS (
    ITEM                       VARCHAR2(20)   NOT NULL,
    CONJUNTO                   VARCHAR2(20)   NOT NULL,
    IDTIPOFT                   NUMBER         NULL,
    IDTIPOFT2                  NUMBER         NULL,
    IDTIPOFT3                  NUMBER         NULL,
    IDTIPOFT4                  NUMBER         NULL,
    IDTIPOFT5                  NUMBER         NULL,
    IDTIPOIPI                  NUMBER         NULL,
    IDCLASSFISCAL              NUMBER         NULL,
    IDFAMILIA                  NUMBER         NULL,
    IDAGRUPAMENTO              NUMBER         NULL,
    ESTADOFT_DETEC             NUMBER         NOT NULL,
    TEXTOESTADOFT_DETEC        VARCHAR2(30)   NULL,
    RAZAOESTADOFT              VARCHAR2(4000) NOT NULL,
    STATUSFT                   NUMBER(3)      NULL,
    TEXTOSTATUSFT              VARCHAR2(200)  NULL,
    RAZAOSUSP                  VARCHAR2(40)   NULL,
    VERSAO                     NUMBER         NOT NULL,
    OBSVERSAO                  VARCHAR2(4000) NULL,
    IDCLIENTE                  NUMBER         NOT NULL,
    REFERENCIA                 VARCHAR2(125)  NOT NULL,
    CODIGOREFERENCIA           VARCHAR2(30)   NULL,
    CODIGOEAN                  VARCHAR2(20)   NULL,
    TIPOABNT                   VARCHAR2(5)    NULL,
    PECASPORUNIDADE            BINARY_DOUBLE  NULL,
    UNIDADESPORCONJUNTO        BINARY_DOUBLE  NULL,
    PECASPORCONJUNTO           BINARY_DOUBLE  NULL,
    EXIGELAUDO                 NUMBER(5)      NOT NULL,
    GRAMATURA                  NUMBER         NULL,
    MULLENMINIMO               BINARY_DOUBLE  NULL,
    CRUSHMINIMO                BINARY_DOUBLE  NULL,
    COLUNAMINIMO               BINARY_DOUBLE  NULL,
    COBBINTMAXIMO              BINARY_DOUBLE  NULL,
    COBBEXTMAXIMO              BINARY_DOUBLE  NULL,
    COBBINT30MAXIMO            BINARY_DOUBLE  NULL,
    COBBEXT30MAXIMO            BINARY_DOUBLE  NULL,
    TESTEFISICOADICIONAL1      BINARY_DOUBLE  NULL,
    PAT_INTERNO                BINARY_DOUBLE  NULL,
    PAT_EXTERNO                BINARY_DOUBLE  NULL,
    ESPESSURA                  BINARY_DOUBLE  NULL,
    UMIDADE                    BINARY_DOUBLE  NULL,
    COMPRESSAO                 BINARY_DOUBLE  NULL,
    PROFUNDIDADEVINCO          BINARY_DOUBLE  NULL,
    FORCADEVINCO1              BINARY_DOUBLE  NULL,
    FORCADEVINCO2              BINARY_DOUBLE  NULL,
    FORCADEVINCO3              BINARY_DOUBLE  NULL,
    COMPOSICAO                 VARCHAR2(40)   NULL,
    FORMATOSIMPLEX             NUMBER         NULL,
    LARGURA                    NUMBER         NULL,
    REFILOLARGURA              NUMBER         NOT NULL,
    COMPRIMENTO                NUMBER         NULL,
    REFILOCOMPRIMENTO          NUMBER         NOT NULL,
    MULTLARG                   NUMBER         NOT NULL,
    MULTCOMP                   NUMBER         NOT NULL,
    ARRANJO                    NUMBER         NULL,
    REFUGOCLIENTE              BINARY_DOUBLE  NOT NULL,
    VINCOSLARGNORISCADOR       CHAR(1)        NOT NULL,
    VINCOLARG1                 NUMBER         NULL,
    VINCOLARG2                 NUMBER         NULL,
    VINCOLARG3                 NUMBER         NULL,
    VINCOLARG4                 NUMBER         NULL,
    VINCOLARG5                 NUMBER         NULL,
    VINCOLARG6                 NUMBER         NULL,
    VINCOLARG7                 NUMBER         NULL,
    VINCOLARG8                 NUMBER         NULL,
    VINCOLARG9                 NUMBER         NULL,
    VINCOLARG10                NUMBER         NULL,
    VINCOSCOMPNORISCADOR       CHAR(1)        NOT NULL,
    VINCOCOMP1                 NUMBER         NULL,
    VINCOCOMP2                 NUMBER         NULL,
    VINCOCOMP3                 NUMBER         NULL,
    VINCOCOMP4                 NUMBER         NULL,
    VINCOCOMP5                 NUMBER         NULL,
    VINCOCOMP6                 NUMBER         NULL,
    VINCOCOMP7                 NUMBER         NULL,
    VINCOCOMP8                 NUMBER         NULL,
    VINCOCOMP9                 NUMBER         NULL,
    VINCOCOMP10                NUMBER         NULL,
    TEARTAPE1                  NUMBER         NOT NULL,
    TEARTAPE2                  NUMBER         NOT NULL,
    TEARTAPE3                  NUMBER         NOT NULL,
    TEARTAPE4                  NUMBER         NOT NULL,
    LAP                        NUMBER         NOT NULL,
    PROLONGLAP                 NUMBER         NOT NULL,
    LAPNOCOMP                  NUMBER(5)      NOT NULL,
    TEXTO_LAPNOCOMP            VARCHAR2(30)   NULL,
    LAPINTERNO                 NUMBER(5)      NOT NULL,
    TEXTO_LAPINTERNO           VARCHAR2(30)   NULL,
    LAPPRIMVINCO               NUMBER(5)      NOT NULL,
    REFILADO                   NUMBER(5)      NOT NULL,
    REJEITO                    NUMBER         NOT NULL,
    REJEITOPECAS               NUMBER         NOT NULL,
    RESINAINTERNA              NUMBER         NOT NULL,
    RESINAINTERNASN            NUMBER         NOT NULL,
    RESINAEXTERNA              NUMBER         NOT NULL,
    RESINAEXTERNASN            NUMBER         NOT NULL,
    ENDURECEDORMIOLO           VARCHAR2(10)   NULL,
    ENDURECEDORMIOLSN          NUMBER         NOT NULL,
    FECHAMENTO                 VARCHAR2(30)   NULL,
    GRAMPOS                    NUMBER         NULL,
    AMARRADO                   NUMBER(5)      NOT NULL,
    FITILHOSLARGPACOTE         NUMBER         NULL,
    FITILHOSCOMPPACOTE         NUMBER         NULL,
    PALETIZADO                 NUMBER(5)      NOT NULL,
    PACOTESLARGURA             NUMBER         NULL,
    PACOTESCOMPRIMENTO         NUMBER         NULL,
    PACOTESALTURA              NUMBER         NULL,
    PECASPORPACOTE             NUMBER         NULL,
    PECASPORPALETE             NUMBER         NULL,
    PACOTESPORPALETE           NUMBER         NULL,
    UNIDADESPORPALETE          BINARY_DOUBLE  NULL,
    FITASLARGPALETE            NUMBER         NULL,
    FITASCOMPPALETE            NUMBER         NULL,
    FACESOPPOSTAS              NUMBER(5)      NOT NULL,
    ESPELHO                    NUMBER(5)      NOT NULL,
    CANTONEIRAS                NUMBER(5)      NOT NULL,
    FILME                      NUMBER(5)      NOT NULL,
    ORELHASINVERTIDAS          NUMBER(5)      NOT NULL,
    FACA                       VARCHAR2(30)   NULL,
    CODFI                      VARCHAR2(30)   NULL,
    COR1                       VARCHAR2(15)   NULL,
    CONSUMOCOR1                NUMBER         NULL,
    VISCOSIDADECOR1            NUMBER         NULL,
    COR2                       VARCHAR2(15)   NULL,
    CONSUMOCOR2                NUMBER         NULL,
    VISCOSIDADECOR2            NUMBER         NULL,
    COR3                       VARCHAR2(15)   NULL,
    CONSUMOCOR3                NUMBER         NULL,
    VISCOSIDADECOR3            NUMBER         NULL,
    COR4                       VARCHAR2(15)   NULL,
    CONSUMOCOR4                NUMBER         NULL,
    VISCOSIDADECOR4            NUMBER         NULL,
    COR5                       VARCHAR2(15)   NULL,
    CONSUMOCOR5                NUMBER         NULL,
    VISCOSIDADECOR5            NUMBER         NULL,
    COR6                       VARCHAR2(15)   NULL,
    CONSUMOCOR6                NUMBER         NULL,
    VISCOSIDADECOR6            NUMBER         NULL,
    NRCORES                    NUMBER         NULL,
    IMPCOMREGISTRO             NUMBER(5)      NOT NULL,
    DETALHECV                  NUMBER(5)      NOT NULL,
    TOLMAIS                    NUMBER         NOT NULL,
    TOLMENOS                   NUMBER         NOT NULL,
    TIPOOBS1                   VARCHAR2(15)   NULL,
    OBS1                       VARCHAR2(255)  NULL,
    TIPOOBS2                   VARCHAR2(15)   NULL,
    OBS2                       VARCHAR2(255)  NULL,
    TIPOOBS3                   VARCHAR2(15)   NULL,
    OBS3                       VARCHAR2(255)  NULL,
    TIPOOBS4                   VARCHAR2(15)   NULL,
    OBS4                       VARCHAR2(255)  NULL,
    TIPOOBS5                   VARCHAR2(15)   NULL,
    OBS5                       VARCHAR2(255)  NULL,
    TIPOOBS6                   VARCHAR2(15)   NULL,
    OBS6                       VARCHAR2(255)  NULL,
    TIPOOBS7                   VARCHAR2(15)   NULL,
    OBS7                       VARCHAR2(255)  NULL,
    TIPOOBS8                   VARCHAR2(15)   NULL,
    OBS8                       VARCHAR2(255)  NULL,
    LARGURAINTERNA             NUMBER         NULL,
    COMPRIMENTOINTERNO         NUMBER         NULL,
    ALTURAINTERNA              NUMBER         NULL,
    LARGPECA                   NUMBER         NULL,
    COMPPECA                   NUMBER         NULL,
    DIMADIC1                   NUMBER         NULL,
    DIMADIC2                   NUMBER         NULL,
    DIMADIC3                   NUMBER         NULL,
    DIMADIC4                   NUMBER         NULL,
    DIMADIC5                   NUMBER         NULL,
    DIMADIC6                   NUMBER         NULL,
    CONTRAONDA                 CHAR(1)        NOT NULL,
    IMPRIMELOGOTIPO            NUMBER         NOT NULL,
    COMISSAODEVENDAS           BINARY_DOUBLE  NOT NULL,
    USUARIOCRIACAO             NUMBER         NULL,
    USUARIO                    NUMBER         NULL,
    PESOADIC                   BINARY_DOUBLE  NULL,
    CUSTOUNITADIC              BINARY_DOUBLE  NULL,
    DATAMODIF                  DATE           NULL,
    DATACRIACAO                DATE           NULL,
    COMPPACOTE                 NUMBER         NULL,
    LARGPACOTE                 NUMBER         NULL,
    ALTURAPACOTE               NUMBER         NULL,
    COMMPALETEFECHADO          NUMBER         NULL,
    LARGPALETEFECHADO          NUMBER         NULL,
    ALTURAPALETEFECHADO        NUMBER         NULL,
    POROSIDADEMINIMO           BINARY_DOUBLE  NULL,
    PESOCAIXA                  BINARY_DOUBLE  NULL,
    PROJETO                    VARCHAR2(50)   NULL,
    REFILOONDULADEIRA          BINARY_DOUBLE  NULL,
    TIPOCUSTOEXTRA             NUMBER         NULL,
    TRAVACOMPOSICAO            NUMBER         NOT NULL,
    DESCRTRAVACOMPOSICAO       VARCHAR2(50)   NULL,
    PRECO_NEGOCIADO            BINARY_DOUBLE  NULL,
    REFILOONDORCAM             NUMBER         NULL,
    REFILOCOMPORCAM            NUMBER         NULL,
    GRUPOPALETIZACAO           VARCHAR2(20)   NULL,
    PATHFIGURADOLASTRO         VARCHAR2(255)  NULL,
    PATHFIGURADAFT             VARCHAR2(255)  NULL,
    PRESSAODEARQUEAMENTO       NUMBER         NULL,
    EMPILHAMENTOMAXIMO         NUMBER         NULL,
    IDPALETE                   NUMBER         NULL,
    REFERENCIAGRUPOPALETIZACAO VARCHAR2(125)  NULL,
    CODIGOERP                  VARCHAR2(30)   NULL,
    IDUNICOREGISTRO            RAW(16)        NOT NULL,
    FLAGESTOQUEOUTERCEIROS     NUMBER         NOT NULL,
    DESCFLAGESTOQUEOUTERCEIROS VARCHAR2(30)   NULL,
    NRPEDSPILOTO               NUMBER         NULL,
    AREAUTILCEDIDAFACA         BINARY_DOUBLE  NOT NULL,
    AREABRUTAPECACOMREFILOS    BINARY_DOUBLE  NULL,
    AREABRUTAPECA              BINARY_DOUBLE  NULL,
    AREALIQUIDAPECA            BINARY_DOUBLE  NULL,
    AREABRUTACHAPA             BINARY_DOUBLE  NULL,
    AREALIQUIDACHAPA           BINARY_DOUBLE  NULL,
    VOLUMEPALETEFECHADOM3      BINARY_DOUBLE  NULL,
    VOLUMEPACOTEFECHADOM3      BINARY_DOUBLE  NULL,
    IDUSUARIOANALISE           NUMBER         NULL,
    PRECOFERRAMENTAS           BINARY_DOUBLE  NULL,
    QUANTPREVISTA              NUMBER         NOT NULL,
    RESUMOCHAPA                NUMBER         NULL,
    COMPLEMENTOCHAPA           NUMBER         NULL,
    CONSTRAINT PK_ITENS PRIMARY KEY (ITEM)
)
