CREATE TABLE MAQUINA (
    MAQ_ID                          NUMBER          NOT NULL,
    MAQUINA                         VARCHAR2(50)    NOT NULL,
    NOMEMAQUINA                     VARCHAR2(50)    NOT NULL,
    TIPO                            NUMBER          NOT NULL,
    FACOES                          NUMBER(3)       NOT NULL, -- tinyint
    LARGUTILMAX                     NUMBER          NOT NULL,
    LARGMINCHAPA                    NUMBER          NOT NULL,
    LARGMAXCHAPA                    NUMBER          NOT NULL,
    COMPMINCHAPA                    NUMBER          NULL,
    COMPMAXCHAPA                    NUMBER          NULL,
    REFILOMIN                       NUMBER          NULL,
    REFILOMAX                       NUMBER          NULL,
    FACAS                           NUMBER          NULL,
    PERMITEMISTURARFERRAMENTAS      CHAR(1)         NOT NULL, -- bit
    IDTIPOVINCOPADRAO               NUMBER          NULL,
    TEARTAPE                        NUMBER          NOT NULL,
    RESINAINTERNA                   NUMBER(5)       NULL,    -- smallint
    RESINAEXTERNA                   NUMBER(5)       NULL,
    ENDURECEDORMIOLO                NUMBER          NULL,
    ROTACAOMAXIMA                   BINARY_DOUBLE   NULL,
    CUSTOHORA                       BINARY_DOUBLE   NULL,
    CUSTOMETRO                      BINARY_DOUBLE   NULL,
    CUSTOMETROQUAD                  BINARY_DOUBLE   NULL,
    FORMATOPADRAO                   VARCHAR2(4000)  NULL,
    UNIDPRODUTIVIDADE               NUMBER(5)       NOT NULL,
    DESCUNIDPRODUTIVIDADE           VARCHAR2(10)    NULL,
    SETUP                           NUMBER          NOT NULL,
    PRODM2                          NUMBER          NOT NULL,
    PRODBATIDAS                     NUMBER          NOT NULL,
    PRODKG                          NUMBER          NOT NULL,
    PRODMAQUINA                     NUMBER          NULL,
    HOMENSTURMA                     NUMBER          NULL,
    GANTT                           NUMBER(5)       NOT NULL,
    NRDECORES                       NUMBER          NULL,
    LOGGANTT                        NUMBER(5)       NULL,
    COMPMINCONJ                     NUMBER          NOT NULL,
    IDGRUPOMAQUINA                  NUMBER          NULL,
    PRODUTIVIDADEPADRAO             NUMBER          NOT NULL,
    EFICIENCIAPADRAO                NUMBER          NOT NULL,
    TAREFAATUAL                     VARCHAR2(45)    NULL,
    INICIOTAREFAATUAL               DATE            NULL,
    FIMPREVTAREFAATUAL              DATE            NULL,
    PARADAATUAL                     NUMBER          NULL,
    INICIOPARADAATUAL               DATE            NULL,
    FIMPREVPARADAATUAL              DATE            NULL,
    IDSECAOMAQUINAPARADAATUAL       NUMBER          NULL,
    PROGRAMARPRODUCAO               CHAR(1)         NOT NULL, -- bit
    DESATIVADA                      NUMBER(5)       NOT NULL,
    CODIGOERP                       VARCHAR2(30)    NULL,
    PERDALIMITEAVISO                NUMBER          NOT NULL,
    UNIDADEAPONTCONJUGACAO          NUMBER          NOT NULL,
    TESTEPORBOLETIM                 NUMBER          NOT NULL,
    IDJORNADA                       NUMBER          NULL,
    DISTMINVINCOs                   NUMBER          NOT NULL,
    IDCENTROCUSTO                   NUMBER          NULL,
    IDCENTROCUSTOMAQ                NUMBER          NULL,
    IDSESSAODB                       NUMBER          NULL,
    PORCMINLARGURARESINADA           NUMBER          NULL,
    CARGAMAQLOTE                     NUMBER          NOT NULL,
    VALIDAINTERSECCAOAPONTAMENTO     NUMBER          NOT NULL,
    DESCVALIDAINTERSECCAOAPONT       VARCHAR2(255)   NULL,
    VALIDABURACOAPONTAMENTO          NUMBER          NOT NULL,
    DESCVALIDABURACOAPONTAMENTO      VARCHAR2(255)   NULL,
    CONSEGUIREFILARSOMENTEUMLADO     NUMBER(3)       NOT NULL, -- tinyint
    IDUNIDADEFABRIL                  NUMBER          NULL,
    REFILEDIRETOPRENSA               CHAR(1)         NOT NULL, -- bit
    AREAM2PERDIDAPORCONJUGACAO       NUMBER          NOT NULL,
    AREAM2PERDIDOTROCAFORMATO        NUMBER          NOT NULL,
    DIFPORCPRODUTMAQFT_MENOS         NUMBER          NOT NULL,
    DIFPORCPRODUTMAQFT_MAIS          NUMBER          NOT NULL,
    PEDIDOMINIMOM2                   NUMBER          NOT NULL,
    PEDIDOMINIMOKG                   NUMBER          NOT NULL,
    LIMITAMINIMOACESSORIO            CHAR(1)         NOT NULL, -- bit
    DISPONIVELLOTENOVO               CHAR(1)         NOT NULL, -- bit
    PERDAPRODUCAOPERC                BINARY_DOUBLE   NOT NULL,
    PERDAPRODUCAOPECAS               BINARY_DOUBLE   NOT NULL,
    DESLOCMAXIMPORTABOBINAS_MM       NUMBER(5)       NOT NULL,
    LARGURALIMITEESTABILIDADEPILHA   NUMBER(5)       NOT NULL,
    COMPRIMENTOREFOGOGUILHOTINA      NUMBER          NULL,
    HABILITARINTEGRACAOESTEIRAOND    CHAR(1)         NOT NULL, -- bit
    CONSTRAINT PK_MAQUINA PRIMARY KEY (MAQ_ID)
)
