CREATE TABLE PEDIDOS (
    IDPEDIDOS               NUMBER          NOT NULL,
    PEDIDO                  VARCHAR2(21)    NOT NULL,
    ITEM                    VARCHAR2(20)    NOT NULL,
    ITEMPEDIDO              VARCHAR2(4)     NULL,
    IDPEDVENDA              NUMBER          NULL,
    IDITEMPEDVENDA          NUMBER          NULL,
    STATUSPEDIDO            NUMBER          NOT NULL,
    DESCRSTATUSPEDIDO       VARCHAR2(30)    NULL,
    SUSPENSO                NUMBER(5)       NOT NULL,  -- smallint
    SUSPOUCANCEL            VARCHAR2(10)    NULL,
    VERSAO                  NUMBER          NOT NULL,
    IDCLIENTE               NUMBER          NOT NULL,
    IDLOJA                  NUMBER          NOT NULL,
    IDLOCALENTREGA          NUMBER          NOT NULL,
    IDLOCALCOBRANCA         NUMBER          NOT NULL,
    REFERENCIA              VARCHAR2(125)   NOT NULL,
    CODIGOREFERENCIA        VARCHAR2(30)    NULL,
    CODIGOEAN               VARCHAR2(20)    NULL,
    TIPOABNT                VARCHAR2(5)     NULL,
    IDTIPOFT                NUMBER          NULL,
    IDTIPOFT2               NUMBER          NULL,
    IDTIPOFT3               NUMBER          NULL,
    IDTIPOFT4               NUMBER          NULL,
    IDTIPOFT5               NUMBER          NULL,
    PECASPORUNIDADE         BINARY_DOUBLE   NULL,
    UNIDADESPORCONJUNTO     BINARY_DOUBLE   NULL,
    PECASPORCONJUNTO        BINARY_DOUBLE   NULL,
    EXIGELAUDO              NUMBER(5)       NOT NULL,  -- smallint
    GRAMATURA               NUMBER          NULL,
    MULLENMINIMO            BINARY_DOUBLE   NULL,
    CRUSHMINIMO             BINARY_DOUBLE   NULL,
    COLUNAMINIMO            BINARY_DOUBLE   NULL,
    COBBINTMAXIMO           BINARY_DOUBLE   NULL,
    COBBEXTMAXIMO           BINARY_DOUBLE   NULL,
    COBBINT30MAXIMO         BINARY_DOUBLE   NULL,
    COBBEXT30MAXIMO         BINARY_DOUBLE   NULL,
    TESTEFISICOADICIONAL1   BINARY_DOUBLE   NULL,
    PAT_INTERNO             BINARY_DOUBLE   NULL,
    PAT_EXTERNO             BINARY_DOUBLE   NULL,
    ESPESSURA               BINARY_DOUBLE   NULL,
    UMIDADE                 BINARY_DOUBLE   NULL,
    COMPRESSAO              BINARY_DOUBLE   NULL,
    PROFUNDIDADEVINCO       BINARY_DOUBLE   NULL,
    FORCADEVINCO1           BINARY_DOUBLE   NULL,
    FORCADEVINCO2           BINARY_DOUBLE   NULL,
    FORCADEVINCO3           BINARY_DOUBLE   NULL,
    CHAPA                   NUMBER(5)       NOT NULL,
    COMPOSICAO              VARCHAR2(40)    NULL,
    FORMATOSIMPLEX          NUMBER          NULL,
    LARGURA                 NUMBER          NULL,
    REFILOLARGURA           NUMBER          NOT NULL,
    COMPRIMENTO             NUMBER          NULL,
    REFILOCOMPRIMENTO       NUMBER          NOT NULL,
    MULTLARG                NUMBER          NOT NULL,
    MULTCOMP                NUMBER          NOT NULL,
    ARRANJO                 NUMBER          NULL,
    REFUGOCLIENTE           BINARY_DOUBLE   NOT NULL,
    PESOPECA                NUMBER          NULL,
    VINCOSLARGNORISCADOR    CHAR(1)         NOT NULL, -- bit
    VINCOLARG1              NUMBER          NULL,
    VINCOLARG2              NUMBER          NULL,
    VINCOLARG3              NUMBER          NULL,
    VINCOLARG4              NUMBER          NULL,
    VINCOLARG5              NUMBER          NULL,
    VINCOLARG6              NUMBER          NULL,
    VINCOLARG7              NUMBER          NULL,
    VINCOLARG8              NUMBER          NULL,
    VINCOLARG9              NUMBER          NULL,
    VINCOLARG10             NUMBER          NULL,
    VINCOSCOMPNORISCADOR    CHAR(1)         NOT NULL, -- bit
    VINCOCOMP1              NUMBER          NULL,
    VINCOCOMP2              NUMBER          NULL,
    VINCOCOMP3              NUMBER          NULL,
    VINCOCOMP4              NUMBER          NULL,
    VINCOCOMP5              NUMBER          NULL,
    VINCOCOMP6              NUMBER          NULL,
    VINCOCOMP7              NUMBER          NULL,
    VINCOCOMP8              NUMBER          NULL,
    VINCOCOMP9              NUMBER          NULL,
    VINCOCOMP10             NUMBER          NULL,
    TEARTAPE1               NUMBER          NOT NULL,
    TEARTAPE2               NUMBER          NOT NULL,
    TEARTAPE3               NUMBER          NOT NULL,
    TEARTAPE4               NUMBER          NOT NULL,
    LAP                     NUMBER          NOT NULL,
    PROLONGLAP              NUMBER          NOT NULL,
    LAPNOCOMP               NUMBER(5)       NOT NULL,
    LAPINTERNO              NUMBER(5)       NOT NULL,
    LAPPRIMVINCO            NUMBER(5)       NOT NULL,
    REFILADO                NUMBER(5)       NOT NULL,
    REJEITO                 NUMBER          NOT NULL,
    REJEITOPECAS            NUMBER          NOT NULL,
    RESINAINTERNA           NUMBER          NOT NULL,
    RESINAINTERNASN         NUMBER          NOT NULL,
    RESINAEXTERNA           NUMBER          NOT NULL,
    RESINAEXTERNASN         NUMBER          NOT NULL,
    ENDURECEDORMIOLO        VARCHAR2(10)    NULL,
    ENDURECEDORMIOLSN       NUMBER          NOT NULL,
    FECHAMENTO              VARCHAR2(30)    NULL,
    GRAMPOS                 NUMBER          NULL,
    AMARRADO                NUMBER(5)       NOT NULL,
    FITILHOSLARGPACOTE      NUMBER          NULL,
    FITILHOSCOMPPACOTE      NUMBER          NULL,
    PALETIZADO              NUMBER(5)       NOT NULL,
    DESCRPALETIZADO         VARCHAR2(30)    NULL,
    PACOTESLARGURA          NUMBER          NULL,
    PACOTESCOMPRIMENTO      NUMBER          NULL,
    PACOTESALTURA           NUMBER          NULL,
    PECASPORPACOTE          NUMBER          NULL,
    PECASPORPALETE          NUMBER          NULL,
    UNIDADESPORPALETE       BINARY_DOUBLE   NULL,
    PACOTESPORPALETE        NUMBER          NULL,
    FITASLARGPALETE         NUMBER          NULL,
    FITASCOMPPALETE         NUMBER          NULL,
    FACESOPPOSTAS           NUMBER(5)       NOT NULL,
    ESPELHO                 NUMBER          NOT NULL,
    CANTONEIRAS             NUMBER(5)       NOT NULL,
    FILME                   NUMBER(5)       NOT NULL,
    ORELASINVERTIDAS        NUMBER(5)       NOT NULL,
    FACA                    VARCHAR2(30)    NULL,
    CODFI                   VARCHAR2(30)    NULL,
    COR1                    VARCHAR2(15)    NULL,
    CONSUMOCOR1             NUMBER          NULL,
    VISCOSIDADECOR1         NUMBER          NULL,
    COR2                    VARCHAR2(15)    NULL,
    CONSUMOCOR2             NUMBER          NULL,
    VISCOSIDADECOR2         NUMBER          NULL,
    COR3                    VARCHAR2(15)    NULL,
    CONSUMOCOR3             NUMBER          NULL,
    VISCOSIDADECOR3         NUMBER          NULL,
    COR4                    VARCHAR2(15)    NULL,
    CONSUMOCOR4             NUMBER          NULL,
    VISCOSIDADECOR4         NUMBER          NULL,
    COR5                    VARCHAR2(15)    NULL,
    CONSUMOCOR5             NUMBER          NULL,
    VISCOSIDADECOR5         NUMBER          NULL,
    COR6                    VARCHAR2(15)    NULL,
    CONSUMOCOR6             NUMBER          NULL,
    VISCOSIDADECOR6         NUMBER          NULL,
    NRCORES                 NUMBER          NULL,
    IMPCOMREGISTRO          NUMBER(5)       NOT NULL,
    DETALHECV               NUMBER(5)       NOT NULL,
    TOLMAIS                 NUMBER          NOT NULL,
    TOLMENOS                NUMBER          NOT NULL,
    CONTRAONDA              CHAR(1)         NOT NULL, -- bit
    TIPOOBS1                VARCHAR2(15)    NULL,
    OBS1                    VARCHAR2(255)   NULL,
    TIPOOBS2                VARCHAR2(15)    NULL,
    OBS2                    VARCHAR2(255)   NULL,
    TIPOOBS3                VARCHAR2(15)    NULL,
    OBS3                    VARCHAR2(255)   NULL,
    TIPOOBS4                VARCHAR2(15)    NULL,
    OBS4                    VARCHAR2(255)   NULL,
    TIPOOBS5                VARCHAR2(15)    NULL,
    OBS5                    VARCHAR2(255)   NULL,
    TIPOOBS6                VARCHAR2(15)    NULL,
    OBS6                    VARCHAR2(255)   NULL,
    TIPOOBS7                VARCHAR2(15)    NULL,
    OBS7                    VARCHAR2(255)   NULL,
    TIPOOBS8                VARCHAR2(15)    NULL,
    OBS8                    VARCHAR2(255)   NULL,
    TIPOOBS9                VARCHAR2(15)    NULL,
    OBS9                    VARCHAR2(255)   NULL,
    DATAENTREGA1            DATE            NOT NULL,
    DATAENTREGA2            DATE            NOT NULL,
    QUANTIDADEPEDIDA        NUMBER          NOT NULL,
    QUANTIDADEPEDIDAMIN     NUMBER          NULL,
    QUANTIDADEPEDIDAMAX     NUMBER          NULL,
    TIPOENTREGA             NUMBER          NOT NULL,
    DESCTIPOENTREGA         VARCHAR2(10)    NULL,
    LARGURAINTERNA          NUMBER          NULL,
    COMPRIMENTOINTERNO      NUMBER          NULL,
    ALTURAINTERNA           NUMBER          NULL,
    LARGPECA                NUMBER          NULL,
    COMPPECA                NUMBER          NULL,
    DIMADIC1                NUMBER          NULL,
    DIMADIC2                NUMBER          NULL,
    DIMADIC3                NUMBER          NULL,
    DIMADIC4                NUMBER          NULL,
    DIMADIC5                NUMBER          NULL,
    DIMADIC6                NUMBER          NULL,
    PRECOVENDA              BINARY_DOUBLE   NULL,
    CUSTOUNITTRANSP         BINARY_DOUBLE   NULL,
    CUSTOUNITVAR            BINARY_DOUBLE   NULL,
    CUSTOUNITFIXO           BINARY_DOUBLE   NULL,
    RESULTOPERACIONAL       BINARY_DOUBLE   NULL,
    MARGEMCONTRHORA         BINARY_DOUBLE   NULL,
    RECEITALIQUIDA          BINARY_DOUBLE   NULL,
    VENDALIQUIDA            BINARY_DOUBLE   NULL,
    MARGEMCONTR             BINARY_DOUBLE   NULL,
    PESOADIC                BINARY_DOUBLE   NULL,
    CUSTOUNITADIC           BINARY_DOUBLE   NULL,
    REGIAOORIGEM            VARCHAR2(4)     NULL,
    DISTANCIA               NUMBER          NULL,
    FRETEINCLUSO            NUMBER          NULL,
    CONDICAODEPAGAMENTO     VARCHAR2(30)    NULL,
    NRDECARROS              NUMBER          NULL,
    CUSTOEXTRAFRETE         BINARY_DOUBLE   NULL,
    PRECOFRETE              BINARY_DOUBLE   NULL,
    PRECOFERRAMENTAS        BINARY_DOUBLE   NOT NULL,
    QUANTPREVISTA           NUMBER          NOT NULL,
    DATACRIACAO             DATE            NULL,
    DATAENTREGAORIGINAL     DATE            NULL,
    NIVELURGENCIA           BINARY_DOUBLE   NOT NULL,
    DATAULTIMAALTERACAOFT   DATE            NULL,
    FLAGESTOQUEOUTERCEIROS  NUMBER          NOT NULL,
    DESCFLAGESTOQUEOUTERCEIROS VARCHAR2(30) NULL,
    ADICIONAL1              VARCHAR2(99)    NULL,
    POSSIVELDATAENTREGA     DATE            NULL,
    TIPODOPEDIDO            NUMBER(5)       NOT NULL,
    DESCRTIPODOPEDIDO       VARCHAR2(30)    NULL,
    TEMPOEXPEDVIAGEM        BINARY_DOUBLE   NULL,
    IMPRIMELOGOTIPO         NUMBER          NOT NULL,
    COMISSAODEVENDAS        BINARY_DOUBLE   NULL,
    VERSAODECUSTO           NUMBER          NULL,
    COMPPACOTE              NUMBER          NULL,
    LARGPACOTE              NUMBER          NULL,
    ALTURAPACOTE            NUMBER          NULL,
    COMMPALETEFECHADO       NUMBER          NULL,
    LARGPALETEFECHADO       NUMBER          NULL,
    ALTURAPALETEFECHADO     NUMBER          NULL,
    POROSIDADEMINIMO        BINARY_DOUBLE   NULL,
    PESOCAIXA               BINARY_DOUBLE   NULL,
    REFILOONDULADERA        BINARY_DOUBLE   NULL,
    TIPOCUSTOEXTRA          NUMBER          NULL,
    PEDCLIENTE              VARCHAR2(20)    NULL,
    ITEMPEDCLIENTE          VARCHAR2(20)    NULL,
    TIPOCAMINHAO            VARCHAR2(20)    NULL,
    CONJUNTO                VARCHAR2(20)    NULL,
    TRAVACOMPOSICAO         NUMBER          NOT NULL,
    DESCRTRAVACOMPOSICAO    VARCHAR2(50)    NULL,
    DATAPROMESSA            DATE            NULL,
    PRECORELACAO            BINARY_DOUBLE   NULL,
    PATHFIGURADOLASTRO      VARCHAR2(255)   NULL,
    PATHFIGURADAFT          VARCHAR2(255)   NULL,
    PRESSAODEARQUEAMENTO    NUMBER          NULL,
    EMPILHAMENTOMAXIMO      NUMBER          NULL,
    GRUPOPALETIZACAO        VARCHAR2(20)    NULL,
    LIBERADOPROGEXPED       NUMBER(5)       NOT NULL,
    IDPALETE                NUMBER          NULL,
    REFERENCIAGRUPOPALETIZACAO VARCHAR2(125) NULL,
    LOTEPILOTO              NUMBER          NULL,
    PEDIDO_ERP              VARCHAR2(30)    NULL,
    ITEM_ERP                VARCHAR2(30)    NULL,
    PRODUTO_ERP             VARCHAR2(30)    NULL,
    DATACRIACAOREGISTRO     DATE            NULL,
    IDUNICOREGISTRO         RAW(16)         NOT NULL, -- uniqueidentifier
    OBSALTERACOES           CLOB            NULL,     -- varchar(-1) → CLOB
    IDUSUARIOULTMODIF       NUMBER          NULL,
    ULTIMAMODIFICACAO       DATE            NOT NULL,
    ORCAMENTO               NUMBER          NULL,
    ITEMORCAMENTO           VARCHAR2(20)    NULL,
    CODREPRESENTANTE        NUMBER          NULL,
    CODSEGMENTO             VARCHAR2(20)    NULL,
    AREAUTILCEDIDAFACA      BINARY_DOUBLE   NOT NULL,
    AREABRUTAPECACOMREFILOS BINARY_DOUBLE   NULL,
    AREABRUTAPECA           BINARY_DOUBLE   NULL,
    AREALIQUIDAPECA         BINARY_DOUBLE   NULL,
    AREABRUTACHAPA          BINARY_DOUBLE   NULL,
    AREALIQUIDACHAPA        BINARY_DOUBLE   NULL,
    VOLUMEPALETEFECHADOM3   BINARY_DOUBLE   NULL,
    VOLUMEPACOTEFECHADOM3   BINARY_DOUBLE   NULL,
    VOLUMEFECHADOPEDIDO     BINARY_DOUBLE   NULL,
    ORIGEMPEDIDO            NUMBER(3)       NOT NULL,
    DESCORIGEMPEDIDO        VARCHAR2(255)   NULL,
    TIPOGERACAOPED          NUMBER(3)       NOT NULL,
    DESCTIPOGERACAOPED      VARCHAR2(255)   NULL,
    IDFILIALEXPEDICAO       NUMBER          NULL,
    QTDIMPRESSOES           NUMBER          NOT NULL,
    DATAHORAPRIMEIRAIMPRESSAO DATE          NULL,
    IDUSUARIOPRIMEIRAIMPRESSAO NUMBER       NULL,
    DATAHORAULTIMAIMPRESSAO DATE            NULL,
    IDUSUARIOULTIMAIMPRESSAO NUMBER        NULL,
    CHAVE_CHAPA             VARCHAR2(255)   NULL,
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (IDPEDIDOS)
)
