CREATE TABLE PEDIDOS (
    IDPEDIDOS               NUMBER          NOT NULL,
    PEDIDO                  VARCHAR2(21)    NOT NULL,
    ITEM                    VARCHAR2(20)    NOT NULL,
    ITEMPEDIDO              VARCHAR2(4)     NULL,
	STATUSPEDIDO            NUMBER          NOT NULL,
    DESCRSTATUSPEDIDO       VARCHAR2(30)    NULL,
	SUSPENSO                NUMBER(5)       NOT NULL,  -- smallint
    SUSPOUCANCEL            VARCHAR2(10)    NULL,
    VERSAO                  NUMBER          NOT NULL,
    IDCLIENTE               NUMBER          NOT NULL,
    REFERENCIA              VARCHAR2(125)   NOT NULL,
    CODIGOREFERENCIA        VARCHAR2(30)    NULL,
    TIPOABNT                VARCHAR2(5)     NULL,
    PECASPORUNIDADE         BINARY_DOUBLE   NULL,
	IDTIPOFT2               NUMBER          NULL,
    UNIDADESPORCONJUNTO     BINARY_DOUBLE   NULL,
    PECASPORCONJUNTO        BINARY_DOUBLE   NULL,
    EXIGELAUDO              NUMBER(5)       NOT NULL,  -- smallint
    GRAMATURA               NUMBER          NULL,
    MULLENMINIMO            BINARY_DOUBLE   NULL,
    CRUSHMINIMO             BINARY_DOUBLE   NULL,
    COLUNAMINIMO            BINARY_DOUBLE   NULL,
    COBBINTMAXIMO           BINARY_DOUBLE   NULL,
    COBBEXTMAXIMO           BINARY_DOUBLE   NULL,
    ESPESSURA               BINARY_DOUBLE   NULL,
    COMPRESSAO              BINARY_DOUBLE   NULL,
	CHAPA                   NUMBER(5)       NOT NULL,
    COMPOSICAO              VARCHAR2(40)    NULL,
    LARGURA                 NUMBER          NULL,
    REFILOLARGURA           NUMBER          NOT NULL,
    COMPRIMENTO             NUMBER          NULL,
    REFILOCOMPRIMENTO       NUMBER          NOT NULL,
    MULTLARG                NUMBER          NOT NULL,
    MULTCOMP                NUMBER          NOT NULL,
    ARRANJO                 NUMBER          NULL,
    REFUGOCLIENTE           BINARY_DOUBLE   NOT NULL,
    PESOPECA                NUMBER          NULL,
    VINCOLARG1              NUMBER          NULL,
    VINCOLARG2              NUMBER          NULL,
    VINCOLARG3              NUMBER          NULL,
    VINCOCOMP1              NUMBER          NULL,
    VINCOCOMP2              NUMBER          NULL,
    VINCOCOMP3              NUMBER          NULL,
    VINCOCOMP4              NUMBER          NULL,
    VINCOCOMP5              NUMBER          NULL,
    LAP                     NUMBER          NOT NULL,
    PROLONGLAP              NUMBER          NOT NULL,
	LAPNOCOMP               NUMBER(5)       NOT NULL,
    LAPINTERNO              NUMBER(5)       NOT NULL,
    LAPPRIMVINCO            NUMBER(5)       NOT NULL,
    REFILADO                NUMBER(5)       NOT NULL,
    RESINAINTERNA           NUMBER          NOT NULL,
    RESINAINTERNASN         NUMBER          NOT NULL,
    FECHAMENTO              VARCHAR2(30)    NULL,
    AMARRADO                NUMBER(5)       NOT NULL,
    FITILHOSLARGPACOTE      NUMBER          NULL,
    PALETIZADO              NUMBER(5)       NOT NULL,
    DESCRPALETIZADO         VARCHAR2(30)    NULL,
    PACOTESLARGURA          NUMBER          NULL,
    PACOTESCOMPRIMENTO      NUMBER          NULL,
    PACOTESALTURA           NUMBER          NULL,
    PECASPORPACOTE          NUMBER          NULL,
    PECASPORPALETE          NUMBER          NULL,
    UNIDADESPORPALETE       BINARY_DOUBLE   NULL,
    PACOTESPORPALETE        NUMBER          NULL,
    FITASLARGPALETE         NUMBER          NULL,
    FITASCOMPPALETE         NUMBER          NULL,
    ESPELHO                 NUMBER          NOT NULL,
    FILME                   NUMBER(5)       NOT NULL,
    FACA                    VARCHAR2(30)    NULL,
    CODFI                   VARCHAR2(30)    NULL,
    COR1                    VARCHAR2(15)    NULL,
    CONSUMOCOR1             NUMBER          NULL,
    COR2                    VARCHAR2(15)    NULL,
    CONSUMOCOR2             NUMBER          NULL,
	COR3                    VARCHAR2(15)    NULL,
    CONSUMOCOR3             NUMBER          NULL,
	COR4                    VARCHAR2(15)    NULL,
    CONSUMOCOR4             NUMBER          NULL,
	NRCORES                 NUMBER          NULL,
    TOLMAIS                 NUMBER          NOT NULL,
    TOLMENOS                NUMBER          NOT NULL,
    TIPOOBS1                VARCHAR2(15)    NULL,
    OBS1                    VARCHAR2(255)   NULL,
    TIPOOBS2                VARCHAR2(15)    NULL,
    OBS2                    VARCHAR2(255)   NULL,
    TIPOOBS3                VARCHAR2(15)    NULL,
    OBS3                    VARCHAR2(255)   NULL,
    TIPOOBS4                VARCHAR2(15)    NULL,
    OBS4                    VARCHAR2(255)   NULL,
    TIPOOBS5                VARCHAR2(15)    NULL,
    OBS5                    VARCHAR2(255)   NULL,
    TIPOOBS6                VARCHAR2(15)    NULL,
    OBS6                    VARCHAR2(255)   NULL,
    TIPOOBS9                VARCHAR2(15)    NULL,
    OBS9                    VARCHAR2(255)   NULL,
    DATAENTREGA1            DATE            NOT NULL,
    DATAENTREGA2            DATE            NOT NULL,
    QUANTIDADEPEDIDA        NUMBER          NOT NULL,
    QUANTIDADEPEDIDAMIN     NUMBER          NULL,
    QUANTIDADEPEDIDAMAX     NUMBER          NULL,
    TIPOENTREGA             NUMBER          NOT NULL,
    DESCTIPOENTREGA         VARCHAR2(10)    NULL,
    LARGURAINTERNA          NUMBER          NULL,
    COMPRIMENTOINTERNO      NUMBER          NULL,
    ALTURAINTERNA           NUMBER          NULL,
    LARGPECA                NUMBER          NULL,
    COMPPECA                NUMBER          NULL,
    DISTANCIA               NUMBER          NULL,
    CONDICAODEPAGAMENTO     VARCHAR2(30)    NULL,
    DATACRIACAO             DATE            NULL,
    DATAENTREGAORIGINAL     DATE            NULL,
    DATAULTIMAALTERACAOFT   DATE            NULL,
    DESCFLAGESTOQUEOUTERCEIROS VARCHAR2(30) NULL,
    DESCRTIPODOPEDIDO       VARCHAR2(30)    NULL,
    IMPRIMELOGOTIPO         NUMBER          NOT NULL,
    COMPPACOTE              NUMBER          NULL,
    LARGPACOTE              NUMBER          NULL,
    ALTURAPACOTE            NUMBER          NULL,
    COMPALETEFECHADO       NUMBER          NULL,
    LARGPALETEFECHADO       NUMBER          NULL,
    ALTURAPALETEFECHADO     NUMBER          NULL,
    PESOCAIXA               BINARY_DOUBLE   NULL,
    PEDCLIENTE              VARCHAR2(20)    NULL,
    DESCRTRAVACOMPOSICAO    VARCHAR2(50)    NULL,
    PATHFIGURADOLASTRO      VARCHAR2(255)   NULL,
    EMPILHAMENTOMAXIMO      NUMBER          NULL,
    IDPALETE                NUMBER          NULL,
    PEDIDO_ERP              VARCHAR2(30)    NULL,
    ITEM_ERP                VARCHAR2(30)    NULL,
    PRODUTO_ERP             VARCHAR2(30)    NULL,
    DATACRIACAOREGISTRO     DATE            NULL,
    IDUNICOREGISTRO         RAW(16)         NOT NULL, -- uniqueidentifier
    IDUSUARIOULTMODIF       NUMBER          NULL,
    ULTIMAMODIFICACAO       DATE            NOT NULL,
    CODREPRESENTANTE        NUMBER          NULL,
    CODSEGMENTO             VARCHAR2(20)    NULL,
    AREABRUTAPECACOMREFILOS BINARY_DOUBLE   NULL,
    AREABRUTAPECA           BINARY_DOUBLE   NULL,
    AREALIQUIDAPECA         BINARY_DOUBLE   NULL,
    AREABRUTACHAPA          BINARY_DOUBLE   NULL,
    AREALIQUIDACHAPA        BINARY_DOUBLE   NULL,
    VOLUMEPALETEFECHADOM3   BINARY_DOUBLE   NULL,
    VOLUMEPACOTEFECHADOM3   BINARY_DOUBLE   NULL,
    VOLUMEFECHADOPEDIDO     BINARY_DOUBLE   NULL,
    ORIGEMPEDIDO            NUMBER(3)       NOT NULL,
    DESCORIGEMPEDIDO        VARCHAR2(255)   NULL,
    TIPOGERACAOPED          NUMBER(3)       NOT NULL,
    DESCTIPOGERACAOPED      VARCHAR2(255)   NULL,
    CHAVE_CHAPA             VARCHAR2(255)   NULL,
    CONSTRAINT PK_PEDIDOS PRIMARY KEY (IDPEDIDOS)
)

